version: "3.8"

services:
  rundeck:
    image: efo1291/rdeck3.3.4-ans2.9.2:1.0
    container_name: rundeck
    hostname: rundeck
    #mem_limit: 768m
    environment:
      - RUNDECK_GRAILS_URL=http://rundeck.cin.ufpe.br
      - RDECK_JVM_SETTINGS="-Xms768m -Xmx768m"
      - RUNDECK_DATABASE_DRIVER=com.mysql.cj.jdbc.Driver
      - RUNDECK_DATABASE_USERNAME=rundeck
      - RUNDECK_DATABASE_PASSWORD=rundeck
      - RUNDECK_DATABASE_URL=jdbc:mysql://mysql/rundeck?autoReconnect=true&useSSL=false        
    volumes:
      - /etc/ansible:/etc/ansible
      - /home/rundeck/.ssh:/home/rundeck/.ssh

  mysql:
    image: mysql:5.7
    container_name: mysql
    hostname: mysql
    expose:
      - 3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=rundeck
      - MYSQL_USER=rundeck
      - MYSQL_PASSWORD=rundeck
    volumes:
      - dbdata:/var/lib/mysql

  nginx:
    image: nginx:alpine
    container_name: nginx
    hostname: nginx
    ports:
      - 80:80
    environment:
      - TZ=America/Recife
    volumes:
      - ./volumes/default.conf:/etc/nginx/conf.d/default.conf

volumes:
  dbdata:
